# Generated by Django 4.0.6 on 2022-07-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='description')),
                ('remaining_amount', models.DecimalField(decimal_places=5, max_digits=5, verbose_name='remain')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('category', models.CharField(choices=[('Other', 'Other'), ('Clothes', 'Clothes'), ('Food', 'Food'), ('Car', 'Car'), ('Soft', 'Soft')], default='Other', max_length=50, verbose_name='category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
    ]
