# Generated by Django 4.0.6 on 2022-07-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='remaining_amount',
            new_name='remain',
        ),
    ]
