# Generated by Django 4.0.6 on 2022-07-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_product_remain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remain',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='remain'),
        ),
    ]
